### ISSUE TITLE
How to get the output graph?

### ISSUE THREAD

**Issue by 0x80** [dagrejs/dagre#174]
In the docs I read about the output graph [here](https://github.com/cpettitt/dagre/wiki#output-graph), which holds the width and height of the total graph. Where do you get this output from exactly? I've tried dagre.layout() but it seems to return undefined...

``` javascript
var dot = require('graphlib-dot');
var dagred3 = require('dagre-d3');

var g = dot.read("digraph { a->b; }");
var out = dagred3.dagre.layout(g);
//??
```

**Comment by esrahofstede** [comment]
You can use:
    var g = new dagreD3.graphlib.Graph();
    dagre.layout(this.g);
    console.log("width: " + this.g.graph().height);
    console.log("height: " + this.g.graph().width);

**Comment by 0x80** [comment]
Thanks! I'm not working on the project at the moment but I'll give it a try when I get back to it.

**Comment by matanster** [comment]
Thanks, I was wondering about the same.... might be a good idea to make that clear in the documentation..
