### ISSUE TITLE
Upgrade to lodash 4

### ISSUE THREAD

**Issue by robstove** [dagrejs/dagre#200]
Any chance this will be happening?

**Comment by Sidewinder1138** [comment]
The readme says this project is no longer actively developed or maintained. So I'm guessing no.

**Comment by avindra** [comment]
Looks like @sandersky did it already on  https://github.com/ciena-blueplanet/dagre

https://github.com/ciena-blueplanet/dagre/pull/5

**Comment by saumeya** [comment]
Hi, please could you release a new version with `lodash` version >4.17.20 . Lesser version has a vulnerability.

**Comment by lutzroeder** [comment]
@saumeya There is no active maintainer for this project. I started a thread with the previous maintainer and planning to update the README accordingly.
