### ISSUE TITLE
maximum call stack size exceeded when my graph is large 

### ISSUE THREAD

**Issue by xiaoshidetaikuai** [dagrejs/dagre#223]
https://stackoverflow.com/questions/35380984/increasing-stack-size-in-browsers#
I  have the save problem ,when  my graph is too large ,there is 5000 nodes and 4999 lines.

**Comment by xiaoshidetaikuai** [comment]
function horizontalCompaction()   pass1,pass2  the recursion is too deep

**Comment by cpettitt** [comment]
Fixed by #228
