### ISSUE TITLE
Node overlapping

### ISSUE THREAD

**Issue by vadimasadchi** [dagrejs/dagre#229]
https://jsfiddle.net/40afknv8/2/

I have two nodes, 100px and 30px wide, and one edge. If I set small ranksep(i.e. 20), 30px node overlaps another one

If I add the third node of width 100px and add the second edge from 1st to 3rd node, graph becomes normal

Look fiddle for details

**Comment by Kr1an** [comment]
Source: [https://github.com/dagrejs/dagre/wiki](https://github.com/dagrejs/dagre/wiki)

> The graph is updated with layout information. Nodes get the following properties:
> x - the x-coordinate of the center of the node
> y - the y-coordinate of the center of the node

Knowing that x, y stands for center of the node, your example seems fine:

- First node: [0;100] with the center at x = 50
- Nodesep: [100, 120]
- Second node: [120;150] with the center at x = 135

`[{"label":"Kevin Spacey","width":100,"height":45,"x":50,"y":22.5},{"label":"Saul Williams","width":30,"height":45,"x":135,"y":22.5}]`
