### ISSUE TITLE
Git ignore auto-generated code

### ISSUE THREAD

**Issue by lutzroeder** [dagrejs/dagre#233]

**Comment by lutzroeder** [comment]
> +1 for this in general. We do need to include the dist files currently to support bower.

Would it be possible to point `bower` at `https://dagrejs.github.io/project/dagre` instead?  

Unrelated, it might be better to use `https://dagrejs.github.io/dagre/dist` to drop `dist` bits. Repos can provide their own gh-pages and GitHub will automatically mesh them together. Would be future proof in case we're trying to switch?

**Comment by cpettitt** [comment]
If bower supports absolute links that would be great. Even better might be to deprecate the bower release if it is not used by many people. I don't see any easy way to get stats tho.

I'm OK with changing the location of the published dist files. We can leave the old ones for backwards compatibility. If we do change the location we also need to update the wiki links.

**Comment by tylerlong** [comment]
There is a better way to provide people with prebuilt files: https://unpkg.com/dagre@0.8.2/dist/

As long as we update NPM package, https://unpkg.com/dagre/ will be updated automatically.

**Comment by cpettitt** [comment]
Sounds good to me. I think we're getting pulled in from cdnjs in a similar way. Happy to drop bower support. Any volunteers? If not, I should be able to do this over the weekend.
