### ISSUE TITLE
Add community place to ask questions in README

### ISSUE THREAD

**Issue by NtsDK** [dagrejs/dagre#235]
Please add in readme information where I can ask questions about dagre-3d. Maybe email or IM chat.
I have a problem but I think it is not a bug. So I want to ask somebody before opening issues.

**Comment by koosvanderkolk** [comment]
Be free to open issues. We can handle them :-).

**Comment by NtsDK** [comment]
Please, look at [this issue](https://github.com/dagrejs/dagre-d3/issues/318).
I described my problem there but I'm not sure which project it is related - this or dagre-d3.
