### ISSUE TITLE
wrong left position of nodes with different widths

### ISSUE THREAD

**Issue by SebLeich** [dagrejs/dagre#264]
I'm currently working with dagre.js in various projects and everytime the same bug occurs. If the size of the nodes is different the left position of the nodes is wrong.

Example: (example available on https://github.com/SebLeich/dagre-example-for-framed.io)

1) all nodes have the same size, no problem occures:

![image](https://user-images.githubusercontent.com/22755574/56301871-ffd93a80-6138-11e9-9166-af9337a88627.png)

2) one "large" node: big gap on the left side and the nodes are overlapping

![image](https://user-images.githubusercontent.com/22755574/56301930-1aabaf00-6139-11e9-9a2e-4cbfcb76725f.png)

3) .. it seems like the gap is caused by the wrong calculated left position of the node: the whole gap has nearly the right width (i dragged the calculated node from 2 to the right position)

![image](https://user-images.githubusercontent.com/22755574/56302136-6cecd000-6139-11e9-8031-4aeef7e7d8af.png)

How did i program it?

`var g = new dagre.graphlib.Graph();`
`g.setGraph({`
`  ranker: "network-simplex",` //all techniques not working
`  ranksep: 150`
`});`
`g.setDefaultEdgeLabel(function() { return {}; });` // not required
`for(var index in this.data.nodes){`
`  var n = f.data.nodes[index];`
`  var h = $("#node-" + n.id).height();`
`  var w = $("#node-" + n.id).width();`
`  g.setNode(n.id, { label: "node-" + n.id, width: w, height: h });`
`for(var index in n.mayors){`
`  g.setEdge(n.mayors[index].id, n.id);`
`}`
`dagre.layout(g);`
`g.nodes().forEach(function(v) {`
`var m = g.node(v);`
`$(m.label).animate({`
`top: n.y,`
`left: n.x`
`});`
`});`

Second example:

1) exactly the same problem: big gap on the left side of "bank" and overlapping project

![image](https://user-images.githubusercontent.com/22755574/56303226-c35b0e00-613b-11e9-99cd-00a52b46e2ae.png)

Is it a problem of the library or did I do something wrong?

**Comment by gordonwoodhull** [comment]
You may know this already, but `x` and `y` denote the center of the node, not the upper left corner.

The upper left corner would be `[n.x - n.width/2, n.y - n.height/2]`

**Comment by SebLeich** [comment]
You're totally right! It solves my problem, i thought dagre returns the left top corner and not the center of the node. Thank you!
