### ISSUE TITLE
odd drawing of graph

### ISSUE THREAD

**Issue by mx2323** [dagrejs/dagre#279]
<img width="997" alt="dagre" src="https://user-images.githubusercontent.com/528124/64205528-74491780-ce55-11e9-8c19-fd341a150459.png">

hi everyone, im using the dagre integration with react-diagrams. 

i'm using the following graph options - 
```
				rankdir: 'LR',
				ranker: 'longest-path',
				nodesep:50,
				ranksep:100,
```

but the graph that is getting drawn looks... not right. 

the spacing between the rank nodes isn't consistent, and the nodes seem to aligned by the top-edge. 

is the above image normal expected behavior for Dagre?

any info would be helpful, as it'll help me debug whether its an issue with the library i'm using or normal expected behavior with Dagre. 

thanks!

**Comment by mx2323** [comment]
this is due to the library using the value returned by dagre as top-left when it is actually the center of the new node

**Comment by larissa-n** [comment]
Any solutions to this?

**Comment by mx2323** [comment]
yeah this was an integration issue where the library using dagre was misinterpreting the points.
