### ISSUE TITLE
Too slow laying out 1000 node graph.

### ISSUE THREAD

**Issue by alexec** [dagrejs/dagre#297]
I've a 1000+ node graph that takes around 3s to layout (graph.layout) and this going up with more nodes. Any suggestions as to why this might be?

**Comment by gordonwoodhull** [comment]
The algorithms in dagre are more complex than you might think, quadratic or cubic in the size of the graph. So this is normal.

You could try viz.js - graphviz uses the same algorithms but it is highly tuned. It still might be slow though.

**Comment by alexec** [comment]
Thank you for the suggestion - I still want to manually render my graph - which is why Dagre is good - any thoughts+

**Comment by gordonwoodhull** [comment]
If viz.js is fast enough, you can still render it however you want, just let it provide the coordinates.

Here is an [example of dc.graph.js doing this](https://dc-js.github.io/dc.graph.js/simple-viewer.html?layout=dot).

**Comment by alexec** [comment]
thank you @gordonwoodhull - amiright in thinking that uses Cola under the hood please?

**Comment by gordonwoodhull** [comment]
It has a choice of layout libraries in the select in the upper left. 

The above link uses dot, so you could test the speed of viz.js by loading your graph into the browser (nothing uploaded) using the file selector on the right.

**Comment by GordonSmith** [comment]
Quick plug for https://www.npmjs.com/package/@hpcc-js/wasm which includes the latest version of Graphviz compiled to wasm (The viz.js project is now archived).

**Comment by gordonwoodhull** [comment]
Thanks @GordonSmith, I also found [aduh95/viz.js](https://github.com/aduh95/viz.js) which also uses wasm and looks like it has substantial development. 

I haven't upgraded dc.graph.js yet, looking forward to trying these out. Real wasm should be smaller and faster.

**Comment by GordonSmith** [comment]
Didn't know about that - should end up being the same thing (FWIW my tooling goes back to old ActiveX + NAPI wrappers I had for GraphViz back in the day!) - you can kick the wheels here:  https://observablehq.com/@gordonsmith/graphviz-wasm-example

**Comment by alexec** [comment]
I've ended up coding by hand Coffman Graham. This looks to be very fast - might be interesting to port into Dagre as another algo

**Comment by gordonwoodhull** [comment]
Interesting! I take it this replaces network simplex for ranking?

**Comment by alexec** [comment]
correct - I need to do more testing now ...
