### ISSUE TITLE
please update typescript definition

### ISSUE THREAD

**Issue by silentmissile** [dagrejs/dagre#341]
in npm site, "dagre" was renamed to "@dagrejs/dagre"

but "@types/dagre" was not renamed, so when I use @types/dagre, I have to rename node_modules/@types/dagre to node_modules/@types/dagrejs__dagre as a temporary solution.

also, some APIs are missed in @types/dagre

**Comment by lorekadam** [comment]
Hi, 
My solution for this, without folder renaming, is update your `tsconfig` like this
`
"compilerOptions": {
    "paths": {
        "@dagrejs/dagre": ["./node_modules/@types/dagre"]
    }
}
`

**Comment by rustedgrail** [comment]
I've added the types file directly to Dagre as an index.d.ts and released the change to NPM. Does that work?

Also, let me know which APIs are missing and I'll update the types.

**Comment by ZhengYuTay** [comment]
> I've added the types file directly to Dagre as an index.d.ts and released the change to NPM. Does that work?
> 
> Also, let me know which APIs are missing and I'll update the types.

you would need to define them in the package.json with `"files": ["index.d.ts"]` and also have a ` "typings":"index.d.ts",`
