### ISSUE TITLE
dagre layout can't fetch edges

### ISSUE THREAD

**Issue by silentmissile** [dagrejs/dagre#342]
in layout() function in @dagrejs/dagre
https://github.com/dagrejs/dagre/blob/68f49439cf4cd35d41f65a35646b96c77ddfc152/lib/layout.js#L82

inputLabel and layoutLabel are two strings

in line 86, the code assign "points" property to string, that code can't run, the error message is:

TypeError: Cannot create property 'points' on string "my-label"

**Comment by rustedgrail** [comment]
If graph.setEdge has a 3rd argument, it's used as the edgeLabel, so edge didn't always return a string and in the Dagre tests, an object was used for the label.

Regardless, I added an edgeAsObj function in Graphlib and used that in layout.js. Both libraries have been released to NPM.
