### ISSUE TITLE
ERROR in ./node_modules/@dagrejs/graphlib/lib/graph.js 18:2 Module parse failed: Unexpected character '#' (18:2)

### ISSUE THREAD

**Issue by shangzhouwan** [dagrejs/dagre#439]
I used dagre in typescript:

`import {graphlib,layout} from '@dagrejs/dagre';`

in function
`let g = new graphlib.Graph();`

but i got error:
<img width="540" alt="截屏2024-04-10 18 32 26" src="https://github.com/dagrejs/dagre/assets/14013146/e96f33fe-63cf-4215-8f9f-af747cee2bfd">

can you help me?

**Comment by rustedgrail** [comment]
The # has been replaced with _ and new versions have been pushed.

**Comment by shangzhouwan** [comment]
<img width="586" alt="截屏2024-04-12 10 18 50" src="https://github.com/dagrejs/dagre/assets/14013146/2724f99d-4c5e-4a23-9376-f96f2e7c367e">

I re-installed the latest version using npm，but also get the error.

can you help me?

**Comment by jcmcneal** [comment]
Don't know if you're using webpack and babel but adding this babel plugin fixed it for me:

[@babel/plugin-transform-private-methods](https://babeljs.io/docs/babel-plugin-transform-private-methods)

**Comment by linkun-wang** [comment]
> <img alt="截屏2024-04-12 10 18 50" width="586" src="https://private-user-images.githubusercontent.com/14013146/321834680-2724f99d-4c5e-4a23-9376-f96f2e7c367e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTYyODUsIm5iZiI6MTcyMjUxNTk4NSwicGF0aCI6Ii8xNDAxMzE0Ni8zMjE4MzQ2ODAtMjcyNGY5OWQtNGM1ZS00YTIzLTkzNzYtZjk2ZjJlN2MzNjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDEyMzk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2M2JmZDU3M2YwNmY0MzQ5NjNkYTUxMDc4YWZkODk4YWQ3NTQ5YmI1MmQ2ZjI4ZTcyYTgzYTM0MzNiODJmZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lr0zWH4LzB8maksKrkvLLSo5EsRKI56HOVt3D8FPDrA">
> I re-installed the latest version using npm，but also get the error:
> 
> ```
> ERROR in ./node_modules/@dagrejs/graphlib/lib/graph.js 18:14
> Module parse failed: Unexpected token (18:14)
> You may need an appropriate loader to handle this file type.
> ```
> 
> can you help me?

解决了吗？我现在遇到了相同的问题

**Comment by scottsut** [comment]
#436

**Comment by shangzhouwan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
