### ISSUE TITLE
Very bad layout

### ISSUE THREAD

**Issue by loicknuchel** [dagrejs/dagre#462]
Hi,

I'm trying a few configurations and several times I got a full-horizontal layout.
How this result is possible? (hard to do worse :sweat_smile:).

![Screenshot from 2024-11-15 20-08-49](https://github.com/user-attachments/assets/fa43bf90-0d87-4dd5-be1f-b310679833d2)

Is there anything I can do to prevent that?

Thanks!

**Comment by ZahidChandio** [comment]
@loicknuchel, could you please share some code sample. Thanks.

**Comment by rustedgrail** [comment]
Yes, you have the rankdir set to 'LR' (Left to Right) and no edges. Because nothing has an edge, every node is at the top level, so dagre doesn't position anything below any other.

**Comment by loicknuchel** [comment]
Indeed, thanks.
Closing the issue as it was a problem on my side.
