### ISSUE TITLE
Support graphviz-like rank constraints

### ISSUE THREAD

**Issue by RobAu** [dagrejs/dagre#54]
Dot has rank: digraph {A->B; B->C; D->C {rank=same A D}}

example:
![test](https://f.cloud.github.com/assets/2735663/136403/8c3ac9ee-7149-11e2-9cab-524ed29fef6c.png)

It would be nice if your lib supported that as well.

**Comment by JDO2k** [comment]
Hi,
i tried to test this new ranking behaviour here http://cpettitt.github.io/project/dagre-d3/latest/demo/interactive-demo.html , but it seems not to work. Both nodes get rendered on different rankings. Can you help me out here?

By the way great work, i like to use it for some data lineage rendering, therefore i need this ranking function.

Greetings

**Comment by BurkovBA** [comment]
I use dagre with JointJS DirectedGraph and setting node ranks to `min` or `max` doesn't work for me.

I say:

```
                var rectParams = {
                    id: label,
                    size: { width: width, height: height },
                    attrs: {
                        text: { text: label, "font-size": letterSize, "font-family": "monospace" },
                        rect: {
                            width: width, height: height,
                            rx: 5, ry: 5,
                            stroke: "#555"
                        }
                    },
                   rank: "min"
                };
new joint.shapes.basic.Rect(rectParams)
```

and my rank is completely ignored by Dagre. I dived into source code of JointJS, Graphlib and Dagre and found out that JointJS correctly passes rank to Graphlib, which doesn't deal with them at all, but leaves ranks to Dagre. Dagre's `buildLayoutGraph()` function builds a copy of input graph, but fails to preserve ranks. Can you help with this? I'm using Dagre version 0.7.4.

**Comment by uri0610** [comment]
rank is not working on my side too.

**Comment by EmilStenstrom** [comment]
@cpettitt Hi, it seems custom ranking is broken in the latest build. Would you by chance have some time to look at what's gone wrong?
